language: python
matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
      dist: trusty
    - os: linux
      python: 3.7
      dist: trusty
    - os: osx
      python: 2.7
script:
  - python setup.py test
  - python setup.py build
  - pyinstaller -F j2tmpl/cli.py -n j2tmpl
